## jaso file for adding

change_filter =[{'filter':['../assest/hair9.png','../assest/ghoul2.png','../assest/eye1.png','../assest/eye2.png'],
                 'center':[27,66,40,46],
                 'width':[1.5,1,0.2,0.2],
                 'height':[1,1,0.4,0.4],
                 'up':[100,20,5,5],
                 'left':[0,0,0,0],
                'counte':1},
                {'filter': ["../assest/birthday-hat.png"],
                 'center': [27],
                 'width': [1.3],
                 'height': [1],
                 'up': [120],
                 'left': [0],
                 'counte':2},
                {'filter': ["../assest/gold-crown.png"],
                 'center': [27],
                 'width': [1.3],
                 'height': [1],
                 'up': [120],
                 'left': [0],
                 'counte':3},
                {'filter': ["../assest/queens-crown.png"],
                 'center': [27],
                 'width': [1.3],
                 'height': [1],
                 'up': [120],
                 'left': [0],
                 'counte':4},
                {'filter': ["../assest/flower-crown.png"],
                 'center': [27],
                 'width': [1.3],
                 'height': [1],
                 'up': [80],
                 'left': [0],
                 'counte': 5},
                {'filter': ["../assest/funny-sunglass.png"],
                 'center': [27],
                 'width': [1.05],
                 'height': [0.33],
                 'up': [0],
                 'left': [0],
                 'counte': 6},
                {'filter': ['../assest/moustache2.png'],
                 'center': [51],
                 'width': [1],
                 'height': [0.5],
                 'up': [1],
                 'left': [-3],
                 'counte': 7},
                {'filter': ["../assest/beard.png"],
                 'center': [8],
                 'width': [1.1],
                 'height': [1.5],
                 'up': [0],
                 'left': [0],
                 'counte': 8},
                {'filter': ["../assest/tongue.png"],
                 'center': [57],
                 'width': [0.6],
                 'height': [1.2],
                 'up': [-25],
                 'left': [0],
                 'counte': 0},


                ]

