## jaso file for adding

change_filter =[{'filter':['../assest/f02.png','../assest/f04.png'],
                 'center':[27,27],#27
                 'width':[1.2,4],#1.5
                 'height':[0.6,0.75],#0.4
                 'up':[20,0],#-7
                 'left':[0,0],
                'counte':1},
                {'filter': ['../assest/moustache2.png'],
                 'center': [51],
                 'width': [1],
                 'height': [0.5],
                 'up': [1],
                 'left': [-3],
                 'counte': 7},
                {'filter': ["../assest/yas6.png","../assest/yas8.png","../assest/yas5.png",],
                 'center': [51,27,51,],
                 'width': [0.8,1.2,0.5,],
                 'height': [0.5,0.33,1,],
                 'up': [5,-5,-15,],
                 'left': [0,0.5,-40,],
                 'counte':2},
                {'filter': ["../assest/funny-sunglass.png"],
                 'center': [27],
                 'width': [1.05],
                 'height': [0.33],
                 'up': [0],
                 'left': [0],
                 'counte': 6},
                {'filter': ['../assest/f21.png',"../assest/beard.png"],
                 'center': [27,8],
                 'width': [1.2,1.1],
                 'height': [0.33,1.5],
                 'up': [-5,0],
                 'left': [0.5,0],
                 'counte': 7},
                 {'filter': ['../assest/f31.png',"../assest/f22.png","../assest/f33.png"],
                 'center': [27,8,27],
                 'width': [1.3,1.1,1],
                 'height': [0.9,1,0.33],
                 'up': [90,-70,0],
                 'left': [0.5,0,0],
                 'counte': 7},
                {'filter': ["../assest/tongue.png"],
                 'center': [57],
                 'width': [0.6],
                 'height': [1.2],
                 'up': [-25],
                 'left': [0],
                 'counte': 0},


                ]

